### ISSUE TITLE
Morning Session code review

### ISSUE THREAD

**Issue by Rocio01** [DyaryRaoof/book-store#5]
**Greetings**

Great work, nice use of the Bootstrap library.

kind regards.

**Comment by leolpaz** [comment]
Great job so far, really efficient use of javascript, but maybe make the title and author field, required, and give a custom valid message for the user to put unknown in case they don't know the author or the title.

**Comment by lfmnovaes** [comment]
## Great work on your project Dico 🙌

Highlights:
- The javascript logic looks good
- No issues at all while manipulating the storage of books
- Nice work with Bootstrap to look it good 👍 

I have just two small suggestions for your project:
- Clear the `input` fields after adding an item to the book list.
- Also it would look a bit better if the column for the remove button is smaller than the left side (which contains the book description).

**Comment by dicodiaz** [comment]
Implemented. Thank you for your suggestion!
